# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeForm(object):
    def setupUi(self, HomeForm):
        HomeForm.setObjectName("HomeForm")
        HomeForm.resize(640, 400)
        HomeForm.setMinimumSize(QtCore.QSize(640, 400))
        HomeForm.setMaximumSize(QtCore.QSize(640, 400))
        self.gridLayoutWidget = QtWidgets.QWidget(HomeForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 641, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.QWidget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.QWidget.setObjectName("QWidget")
        self.ImageWidget = HorizontalFlipView(self.QWidget)
        self.ImageWidget.setGeometry(QtCore.QRect(20, 20, 370, 210))
        self.ImageWidget.setMinimumSize(QtCore.QSize(370, 210))
        self.ImageWidget.setMaximumSize(QtCore.QSize(370, 210))
        self.ImageWidget.setStyleSheet("background: #5698c3;")
        self.ImageWidget.setObjectName("ImageWidget")
        self.setDesktopButton = PrimaryPushButton(self.QWidget)
        self.setDesktopButton.setGeometry(QtCore.QRect(120, 250, 181, 31))
        self.setDesktopButton.setObjectName("setDesktopButton")
        self.gridLayout.addWidget(self.QWidget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = SubtitleLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = BodyLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.statusLabel = CaptionLabel(self.gridLayoutWidget)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(HomeForm)
        QtCore.QMetaObject.connectSlotsByName(HomeForm)

    def retranslateUi(self, HomeForm):
        _translate = QtCore.QCoreApplication.translate
        HomeForm.setWindowTitle(_translate("HomeForm", "Form"))
        self.setDesktopButton.setText(_translate("HomeForm", "应用到桌面"))
        self.label.setText(_translate("HomeForm", "图像信息"))
        self.label_2.setText(_translate("HomeForm", "来源：向日葵8号气象卫星"))


from qfluentwidgets import BodyLabel, CaptionLabel, HorizontalFlipView, PrimaryPushButton, SubtitleLabel
